# config.yaml

dem:
  path: "Y:/ATD/GIS/Bennett/DEMs/LIDAR/OT 2021/dem_2021_bennett_clip.tif"

#perpendicular_lines created from get_perpendiculars.py
perpendicular_lines:
  path: "Y:/ATD/GIS/Bennett/Valley Widths/Valley_Footprints/Hydraulic Model/Perpendiculars/ME_perps_5m.gpkg"

flow_raster_dict:
  0.25: "Y:/ATD/GIS/Bennett/Valley Widths/Valley_Footprints/Hydraulic Model/Max Depth Rasters/ME/ME_0o25cms.tif"
  0.5: "Y:/ATD/GIS/Bennett/Valley Widths/Valley_Footprints/Hydraulic Model/Max Depth Rasters/ME/ME_0o5cms.tif"
  1: "Y:/ATD/GIS/Bennett/Valley Widths/Valley_Footprints/Hydraulic Model/Max Depth Rasters/ME/ME_1cms.tif"
  2: "Y:/ATD/GIS/Bennett/Valley Widths/Valley_Footprints/Hydraulic Model/Max Depth Rasters/ME/ME_2cms.tif"
  3: "Y:/ATD/GIS/Bennett/Valley Widths/Valley_Footprints/Hydraulic Model/Max Depth Rasters/ME/ME_3cms.tif"
  4: "Y:/ATD/GIS/Bennett/Valley Widths/Valley_Footprints/Hydraulic Model/Max Depth Rasters/ME/ME_4cms.tif"
  5: "Y:/ATD/GIS/Bennett/Valley Widths/Valley_Footprints/Hydraulic Model/Max Depth Rasters/ME/ME_5cms.tif"
  6: "Y:/ATD/GIS/Bennett/Valley Widths/Valley_Footprints/Hydraulic Model/Max Depth Rasters/ME/ME_6cms.tif"
  7: "Y:/ATD/GIS/Bennett/Valley Widths/Valley_Footprints/Hydraulic Model/Max Depth Rasters/ME/ME_7cms.tif"
  8: "Y:/ATD/GIS/Bennett/Valley Widths/Valley_Footprints/Hydraulic Model/Max Depth Rasters/ME/ME_8cms.tif"
  9: "Y:/ATD/GIS/Bennett/Valley Widths/Valley_Footprints/Hydraulic Model/Max Depth Rasters/ME/ME_9cms.tif"
  10: "Y:/ATD/GIS/Bennett/Valley Widths/Valley_Footprints/Hydraulic Model/Max Depth Rasters/ME/ME_10cms.tif"

# The path to the flow_values.json file generated byget_valleys_from_HEC_polys.py
flow_values:
  path: "Y:/ATD/GIS/Bennett/Valley Widths/Valley_Footprints/Hydraulic Model/Depth Leveling Test/Results Inflection/flow_values.json"  # Replace with the actual path to your flow_values.json

output:
  directory: "Y:/ATD/GIS/Bennett/Valley Widths/Valley_Footprints/Hydraulic Model/Depth Leveling Test/Results Inflection/Terrain vs Depth"

logging:
  level: "INFO"
  log_file: "Y:/ATD/GIS/Bennett/Valley Widths/Valley_Footprints/Hydraulic Model/Depth Leveling Test/Results Inflection/Terrain vs Depth/plot_tertrain_vs_depth.log"
